"""empty message

Revision ID: 0981034402fa
Revises: 
Create Date: 2020-02-05 15:19:58.535647

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from user.models import User

# revision identifiers, used by Alembic.
revision = '0981034402fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(User.genders), nullable=True),
    sa.Column('location', sqlalchemy_utils.types.choice.ChoiceType(User.locations), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
