"""empty message

Revision ID: 48ec75927ee5
Revises: 0981034402fa
Create Date: 2020-02-06 10:51:23.785850

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from user import models

# revision identifiers, used by Alembic.
revision = '48ec75927ee5'
down_revision = '0981034402fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sqlalchemy_utils.types.choice.ChoiceType(models.locations), nullable=True),
    sa.Column('min_distance', sa.Integer(), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('min_dating_age', sa.Integer(), nullable=True),
    sa.Column('max_dating_age', sa.Integer(), nullable=True),
    sa.Column('dating_sex', sqlalchemy_utils.types.choice.ChoiceType(models.genders), nullable=True),
    sa.Column('vibration', sa.Boolean(), nullable=True),
    sa.Column('only_matche', sa.Boolean(), nullable=True),
    sa.Column('auto_play', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
